imports:
  - { resource: 'parameters.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
      - '../src/DTO'
      - '../src/Kernel.php'
